### ISSUE TITLE
More flexible format support

### ISSUE THREAD

**Issue by FallenRiteMonk** [WSDOT-GIS/dms-js#1]
Hy,

I just had a look at your parse functionality (since I'm only interested in that at the moment) and found out that you do not support the possibility of having the direction in front of the coordinate (ex.: N 39° 03' 51.420" W 145° 12' 15.780"). Would it somehow be possible to implement that?

also found a different library that uses a different regex that might help:
https://github.com/gmaclennan/parse-dms
but I'd rather use your library as I see the potential in changing more of my code to use more of your functionality.

Thanks

**Comment by JeffJacobson** [comment]
I have no objection to adding additional formats as long as it doesn't break additional functionality. However I currently do not have time to do this myself. You are welcome to make a pull request to add the change yourself, though.

**Comment by JeffJacobson** [comment]
In another issue's comment section, someone recommended https://github.com/nerik/formatcoords for more formatting flexibility.
