### ISSUE TITLE
Westerley longitudes within 1 degree of Greenwich Meridian are incorrectly positive

### ISSUE THREAD

**Issue by puddicombe** [WSDOT-GIS/dms-js#3]
Beyond 1 degree West is fine, but under 1 whole degree the output is positive and matches the equivilent Easterly.

var dmsConversion = require("dms-conversion")
var dmsStringsWest = ["0°0′0″ N", "0°59′59″ W"];
var dmsCoordsWest = dmsStringsWest.map(dmsConversion.parseDms); 
var dmsStringsEast = ["0°0′0″ N", "0°59′59″ E"];
var dmsCoordsEast = dmsStringsEast.map(dmsConversion.parseDms); 
console.log(dmsCoordsWest,dmsCoordsEast);
if (dmsCoordsWest[1] == dmsCoordsEast[1]) {
    console.log("East and West co-ordinates have been converted to be equal but are not!");
    }

=>
[0, 0.9997222222222222]
"East and West co-ordinates have bee…converted to be equal but are not!"

**Comment by puddicombe** [comment]
Suggested fix:

Replace

            if (hemisphere !== null && /[SW]/i.test(hemisphere)) {
                degrees = Math.abs(degrees) * -1;
            }
            if (degrees < 0) {
                output = degrees - minutes - seconds;
            }
            else {
                output = degrees + minutes + seconds;
            }



with

            if (hemisphere !== null && /[SW]/i.test(hemisphere)) {
                output = -Math.abs(degrees) - minutes - seconds;
            } else {
                output = degrees + minutes + seconds;
            }

**Comment by JeffJacobson** [comment]
@puddicombe, I won't be able to work on this for a while. The fastest way to get this fixed would be for you to make a [pull request](https://help.github.com/articles/about-pull-requests/) with your proposed solution.
